### ISSUE TITLE
Handle Startup Arguments

### ISSUE THREAD

**Issue by AVividLight** [Matt-and-Gib/gleemail#22]
Possible way: make all objects pointers, create instances in factories, pass kvpair queues into factories; make polymorphic wrapper for pointers to member functions, provide those to kvpairs.

**Comment by DualJustice** [comment]
One way we could handle this is to have a Startup Code to enter into a STARTUPCODES Setup State. Basically, have a half-second or so delay at the beginning of the program that allows the user to enter "-s", or whatever code we settle on. Then, if this code is entered, glEEmail enters a STARTUPCODES Setup State (like a bios) where the user can enter a string of startup codes to be used in later setup steps.

**Comment by AVividLight** [comment]
Note to self: if you can't figure out what's going on with the (v-tables in) reinterpret_cast'd pointers to member functions, maybe use this: https://en.cppreference.com/w/cpp/utility/functional/function (if available on Arduino)

**Comment by AVividLight** [comment]
Finished in #436b9118a41758521061379d26dccaaa406a6870
