### ISSUE TITLE
Unit Test Binary Search Tree

### ISSUE THREAD

**Issue by AVividLight** [Matt-and-Gib/gleemail#67]
Write unit tests for everything about our implementation of a binary search tree. Also maybe test in Valgrind?

**Comment by angelinakap2** [comment]
Hi @AVividLight, I have some experience in Java and C++ and am interested in open-source contribution for my Intro to Software Engineering class. Would it be possible to add me as a participant to this project?

**Comment by AVividLight** [comment]
@angelinakap2 Hello! Thanks for reaching out, we'd love to work together. Is there a piece of glEEmail that you'd like to work on, or would you prefer to take on some documented issues? Also, is your preference working together or on your own and submitting a pull request at the end? Either way, we'll make sure you're credited for your work.

**Comment by AVividLight** [comment]
We no longer need a BSTree data structure after making significant architectural changes to MorseCode in 3fe9d8bb56eac5d708a5b6a3becc5e0890761716

@angelinakap2 Although this issue is now closed, we'd still love to work together. Please reach out at any point if you'd like to discuss project needs.
