### ISSUE TITLE
General MorseCodeCharPairs Overhaul

### ISSUE THREAD

**Issue by DualJustice** [Matt-and-Gib/gleemail#75]
1. Lop off some layers of the binary search tree.
2. Potentially reassign symbols to the remaining phrases.
3. Replace the spaces with empty strings during the JSON parsing phase.
3. Potentially document the updated tree so that users know which codes are associated with which characters.

**Comment by AVividLight** [comment]
The 'Ole Lopper has struck again (step 1?) https://github.com/Matt-and-Gib/gleemail/commit/227c3ccff56866cf2ba78a90e0ab5f5f6bdf97ac

**Comment by AVividLight** [comment]
@DualJustice this should be closed, right? I think we decided on preserving the MCCP data and rewriting the tree into an array instead.

**Comment by DualJustice** [comment]
@AVividLight I agree, I believe that this issue is either no longer relevant, or has been completed (depending on how you look at it) and should be closed out.
